In [24]:
import requests
from bs4 import BeautifulSoup
import json
import pandas as pd

In [25]:
# scrape the single game shots 
base_url = 'https://understat.com/match/'
match = str(input('Enter the match id: '))
url = base_url + match

In [26]:
# make the request to the website
res = requests.get(url)

In [27]:
soup = BeautifulSoup(res.content, 'lxml')
scripts = soup.find_all('script')

In [28]:
# get the shotsData
strings = scripts[1].string

In [29]:
# strip unnecessary symbols and get only JSON data
ind_start = strings.index("('")+2
ind_end = strings.index("')")

json_data = strings[ind_start:ind_end]
json_data = json_data.encode('utf8').decode('unicode_escape')

# convert string to json format
data = json.loads(json_data)

In [30]:
x = []
y = []
xG = []
team = []
data_away = data['a']
data_home = data['h']

for index in range(len(data_home)):
    for key in data_home[index]:
        if key == 'X':
            x.append(data_home[index][key])
        if key == 'Y':
            y.append(data_home[index][key])
        if key == 'xG':
            xG.append(data_home[index][key])
        if key == 'h_team':
            team.append(data_home[index][key])

for index in range(len(data_away)):
    for key in data_away[index]:
        if key == 'X':
            x.append(data_away[index][key])
        if key == 'Y':
            y.append(data_away[index][key])
        if key == 'xG':
            xG.append(data_away[index][key])
        if key == 'a_team':
            team.append(data_away[index][key])

In [31]:
# create a dataframe
col_names = ['x', 'y', 'xG', 'team']
df = pd.DataFrame([x, y, xG, team], index=col_names)

In [32]:
df = df.T

In [33]:
df

,x,y,xG,team
0,0.9480000305175781,0.4109999847412109,0.44129449129104614,Crystal Palace
1,0.7469999694824219,0.6,0.015614083968102932,Crystal Palace
2,0.925,0.4590000152587891,0.09893310815095901,Crystal Palace
3,0.955999984741211,0.600999984741211,0.07587538659572601,Crystal Palace
4,0.7469999694824219,0.7569999694824219,0.014710091054439545,Crystal Palace
5,0.950999984741211,0.4929999923706055,0.08150634169578552,Crystal Palace
6,0.8909999847412109,0.38299999237060545,0.05142579600214958,Crystal Palace
7,0.7390000152587891,0.33799999237060546,0.01998203992843628,Crystal Palace
8,0.9069999694824219,0.6,0.3893897533416748,Crystal Palace
9,0.955,0.4909999847412109,0.4918178617954254,Crystal Palace
10,0.9059999847412109,0.37900001525878907,0.08893308788537979,Crystal Palace
11,0.8340000152587891,0.544000015258789,0.10265412926673889,Crystal Palace
12,0.9059999847412109,0.35900001525878905,0.13382738828659058,Crystal Palace
13,0.950999984741211,0.5309999847412109,0.5796364545822144,Crystal Palace
14,0.9359999847412109,0.5690000152587891,0.14874619245529175,Crystal Palace
15,0.745999984741211,0.37900001525878907,0.02498585544526577,Crystal Palace
16,0.555,0.605,0.007328184321522713,Crystal Palace
17,0.9519999694824218,0.615,0.3679986596107483,Crystal Palace
18,0.8219999694824218,0.6270000076293946,0.06002671271562576,Crystal Palace
19,0.87,0.6,0.10246826708316803,Crystal Palace
20,0.8030000305175782,0.6530000305175782,0.04009458050131798,Crystal Palace
21,0.9030000305175782,0.5129999923706055,0.025587821379303932,Luton
22,0.8830000305175781,0.6359999847412109,0.053713005036115646,Luton
23,0.8619999694824219,0.48200000762939454,0.03255298361182213,Luton
24,0.965999984741211,0.49599998474121093,0.6594911813735962,Luton
25,0.93,0.5120000076293946,0.1131049320101738,Luton
26,0.860999984741211,0.5479999923706055,0.06610322743654251,Luton
27,0.8640000152587891,0.4759999847412109,0.06723140180110931,Luton
28,0.9,0.4490000152587891,0.06752422451972961,Luton