In [8]:
import re
import requests
import pandas as pd

from bs4 import BeautifulSoup

In [9]:
league = 'premier-league'
div = '1'
country = 'GB'
games = 38

In [10]:
url = f'https://www.transfermarkt.co.uk/{league.lower()}/spieltagtabelle/wettbewerb/{country}{div}?saison_id=2023&spieltag=46'

In [11]:
headers = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
}

In [12]:
response = requests.get(url, headers=headers)

In [13]:
response.status_code

200

In [14]:
soup = BeautifulSoup(response.content, 'html.parser')

In [15]:
teams = []
list = soup.select('td[class="no-border-links hauptlink"]')
for y in range(len(list)):
    team = list[y].text.strip()
    teams.append(team)

In [16]:
table = pd.DataFrame(teams)

In [17]:
for x in range(1, games+1):
    url = f'https://www.transfermarkt.co.uk/{league.lower()}/spieltagtabelle/wettbewerb/{country}{div}?saison_id=2023&spieltag={x}'
    response = requests.get(url, headers=headers)
    response.status_code
    soup = BeautifulSoup(response.content, 'html.parser')
    list = soup.select('td[class="no-border-links hauptlink"]')
    teams = []
    for y in range(len(list)):
        team = list[y].text.strip()
        teams.append(team)
    df_temp = pd.DataFrame(teams)
    df_temp[f'Week {x}'] = range(1, len(df_temp) + 1)
    table = pd.merge(table, df_temp, on=0)

In [18]:
table

,0,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8,Week 9,...,Week 29,Week 30,Week 31,Week 32,Week 33,Week 34,Week 35,Week 36,Week 37,Week 38
0,Man City,3,2,1,1,1,1,1,3,2,...,2,2,2,2,1,1,1,1,1,1
1,Arsenal,4,3,5,5,4,5,3,2,3,...,1,1,1,1,2,2,2,2,2,2
2,Liverpool,12,6,4,3,3,2,4,4,4,...,3,3,3,3,3,3,3,3,3,3
3,Aston Villa,18,9,7,9,7,6,5,5,5,...,4,4,4,5,4,4,4,4,4,4
4,Tottenham,8,5,3,2,2,4,2,1,1,...,5,5,5,4,5,5,5,5,5,5
5,Chelsea,11,14,10,11,13,13,11,11,10,...,9,9,7,9,8,7,7,6,6,6
6,Newcastle,1,8,13,13,11,8,8,8,6,...,11,8,9,8,7,8,8,8,7,7
7,Man Utd,7,11,8,10,12,9,10,10,8,...,6,6,6,6,6,6,6,7,8,8
8,West Ham,10,7,2,4,6,7,7,7,9,...,7,7,8,7,9,9,9,9,9,9
9,Crystal Palace,5,10,11,7,8,10,9,9,11,...,14,14,14,14,14,14,14,14,12,10
10,Brighton,2,1,6,6,5,3,6,6,7,...,8,10,11,11,11,11,12,11,10,11
11,Bournemouth,13,15,16,17,16,17,18,18,18,...,13,12,10,10,10,10,10,10,11,12
12,Fulham,6,13,12,12,9,11,12,12,13,...,12,13,13,13,13,13,13,13,14,13
13,Wolves,15,18,14,14,17,14,14,13,12,...,10,11,12,12,12,12,11,12,13,14
14,Everton,20,20,20,20,20,20,20,20,20,...,15,16,16,15,16,16,15,15,15,15
15,Brentford,9,4,9,8,10,12,13,14,14,...,16,15,15,16,15,15,16,16,16,16
16,Nottm Forest,19,19,19,16,15,16,15,15,15,...,18,17,17,17,17,17,17,17,17,17
17,Luton,16,17,18,19,19,18,16,16,16,...,17,18,18,18,18,18,18,18,18,18
18,Burnley,17,12,15,15,14,15,17,17,17,...,19,19,19,19,19,19,19,19,19,19
19,Sheff Utd,14,16,17,18,18,19,19,19,19,...,20,20,20,20,20,20,20,20,20,20

In [19]:
table.rename(columns={0: 'Team'}, inplace=True)

In [20]:
table.to_excel(f"C:\\Users\\George\\Documents\\Football Analytics\\Data\\{league} Position.xlsx", index=False)